### ISSUE TITLE
Infografia sistemas numericos (matematicas discretas)

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/infografia-Alondra-oss#1]
[Infografia sistemas numericos (matematicas discretas) (2).pdf](https://github.com/user-attachments/files/16742163/Infografia.sistemas.numericos.matematicas.discretas.2.pdf)

**Comment by Johnc-byte** [comment]
redacción y ortografía : 14/14
exposición de ideas centrales : 16/16
organización de ideas centrales : 14/14
uso de imágenes y colores : 14/14
presentación visual : 14/14
referencias : 14/14
presentación : 14/14
calificación final : 20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
